version: '3.4'

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            x-develop:
                watch:
                    - action: sync
                      path: ./src
                      target: /usr/app/
                    - action: rebuild
                      path: package.json
        container_name: mentorchief-frontend
        restart: always
        ports:
            - 4500:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
