version: 2.1

orbs:
  slack: circleci/slack@4.3.0

# commands:
#   notify_slack_error:
#     steps:
#       - slack/notify:
#           event: fail
#           template: basic_fail_1

#   notify_slack_pass:
#     steps:
#       - slack/notify:
#           event: pass
#           template: basic_success_1
jobs:
  Build:
    docker:
    - image: cimg/base:stable
    steps:
    - trigger_slack_notification
    - checkout
    - run: |
        docker build -t mentorme-fe-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM .
        docker save -o ./mentorme-fe-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM.tar mentorme-fe-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM
    - slack/notify:
        event: fail
        template: basic_fail_1
    - slack/notify:
        event: pass
        template: success_tagged_deploy_1workflows
    - setup_remote_docker:
        version: 20.10.14
    - persist_to_workspace:
        root: .
        paths:
          - .

  # Deploy:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - checkout
  #     - run: 
  #         name: Deploy to $CIRCLE_BRANCH server 
  #         command: |
  #           Test="Hello world"
  #           scp ./Docker/mentorme-fe-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM.tar $SSH_USER@$SSH_HOST:~/Docker
  #           ssh $SSH_USER@$SSH_HOST -o "StrictHostKeyChecking=no" -o SendEnv=Test << EOF 
  #           docker load -i ~/Docker/mentorme-fe-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM.tar
  #           cd ~/$CIRCLE_BRANCH
  #           docker-compose up 
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - .
  
workflows:
  mentorme-fe-workflow:
    jobs:
      - Build
      # - Deploy:
      #     requires:
      #       - Build
