version: 2.1

jobs:
  Build:
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - run: |
        export DOCKER_BUILDKIT=1
        mkdir Docker
        docker build -t  mentorme-fe-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM .
        docker save -o ./Docker/mentorme-fe-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM.tar mentorme-fe-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM
    - persist_to_workspace:
        root: .
        paths:
          - .

  # Deploy:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - checkout
  #     - run: 
  #         name: Deploy to $CIRCLE_BRANCH server 
  #         command: |
  #           Test="Hello world"
  #           scp ./Docker/mentorme-fe-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM.tar $SSH_USER@$SSH_HOST:~/Docker
  #           ssh $SSH_USER@$SSH_HOST -o "StrictHostKeyChecking=no" -o SendEnv=Test << EOF 
  #           docker load -i ~/Docker/mentorme-fe-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM.tar
  #           cd ~/$CIRCLE_BRANCH
  #           docker-compose up 
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - .
  
workflows:
  mentorme-fe-workflow:
    jobs:
      - Build
      # - Deploy:
      #     requires:
      #       - Build
