const jobTitles = [
	// General Software Development
	"Software Developer",
	"Software Engineer",
	"Full Stack Developer",
	"Technical Lead",
	"Technical Architect",
	"Application Developer",
	"System Programmer",
	"Coding Specialist",
	"Solution Architect",
	"Platform Developer",
	// Frontend Development
	"Frontend Developer",
	"UI Developer",
	"Web Developer",
	"Frontend Engineer",
	"Interactive Developer",
	"SPA Developer",
	// Backend Development
	"Backend Developer",
	"API Developer",
	"Server-Side Developer",
	"Database Developer",
	"Middleware Developer",
	// Mobile Development
	"Mobile Developer",
	"iOS Developer",
	"Android Developer",
	"Cross-Platform Developer",
	"Mobile App Engineer",
	"Mobile Software Developer",
	// Cloud & DevOps
	"DevOps Engineer",
	"Cloud Engineer",
	"Platform Engineer",
	"Infrastructure Engineer",
	"Cloud Architect",
	"Site Reliability Engineer",
	"Cloud Operations Engineer",
	"Kubernetes Developer",
	// Data and AI
	"Data Scientist",
	"Machine Learning Engineer",
	"AI Developer",
	"Data Engineer",
	"Data Analyst",
	"Data Architect",
	"Big Data Engineer",
	"Data Visualization Specialist",
	"BI Developer",
	"Data Platform Engineer",
	"Predictive Analytics Developer",
	"AI Researcher",
	// Game Development
	"Game Developer",
	"Game Designer",
	"Game Programmer",
	"Game AI Developer",
	"3D Graphics Developer",
	"Gameplay Developer",
	"Game Systems Developer",
	// Testing and QA
	"QA Engineer",
	"Test Engineer",
	"Automation Tester",
	"Performance Tester",
	"Security Tester",
	"Quality Assurance Analyst",
	"Software Tester",
	// Specialized Roles
	"Cybersecurity Engineer",
	"Blockchain Developer",
	"Embedded Developer",
	"IoT Developer",
	"Robotics Engineer",
	"AR Developer",
	"VR Developer",
	"Firmware Developer",
	"Accessibility Specialist",
	"Quantum Computing Developer",
	"Bioinformatics Developer",
	"GIS Developer",
	"Simulation Developer",
	"Hardware Integration Developer",
	"Telecommunications Engineer",
	// Management and Leadership
	"Technical Lead",
	"Engineering Manager",
	"CTO",
	"Product Manager",
	"Program Manager",
	"Scrum Master",
	"Agile Coach",
	"Delivery Manager",
	"Software Development Manager",
	"Technical Program Manager",
	"Head of Engineering",
	// Variations and Miscellaneous
	"Web Developer",
	"ERP Developer",
	"E-commerce Developer",
	"Open Source Contributor",
	"Performance Engineer",
	"API Integration Developer",
	"Legacy Systems Developer",
	"DevOps Automation Engineer",
	"Mobile Framework Engineer",
	"Networking Developer",
	"System Integration Developer",
	"IT Engineer",
	"Cloud Security Engineer",
	"AR/VR Developer",
	"Business Systems Developer",
	"Workflow Developer",
	"Infrastructure Architect",
	"Distributed Systems Developer",
	"Streaming Systems Developer",
	"Natural Language Processing Developer",
	"Functional Programmer",
	"Graphics Programmer",
	"Streaming Media Developer",
	"Desktop Developer",
	"Load Tester",
	"Data Pipeline Developer",
	"Cloud Migration Engineer",
	"Operations Developer",
	"Algorithm Engineer",
	"Computational Scientist",
	"Game Engine Developer",
	"Interactive Experience Developer",
	"Wearable Device Developer",
	"AI Ethics Specialist",
	"E-Learning Developer",
	"Tech Support Engineer",
	"Low-Code Developer",
	"No-Code Developer",
	"DevTools Developer",
	"Crypto Developer",
	"Performance Optimization Engineer",
	"Real-Time Systems Developer",
	"Search Engine Developer",
	"Compiler Developer",
	"Localization Engineer"
];

export default jobTitles;
